{
  "title": "Live Dungeon",
  "description": "An old MMORPG called Live Dungeon. Before the service was terminated, Kyotani Tsutomu made full use of 5 notebook PCs to clear the game and was invited to a different world. And then, Tsutomu was speechless when he saw a live relay of a dungeon capture in the different world. They bulldozed through without any thought of strategy. The misfortune of getting the healer position. Tsutomu reinstated the White Mage that had always been his favorite in games and aimed to conquer the dungeon to find the key to his escape from the different world.",
  "artist": "Kotori Ryou",
  "author": "dy Reitou, Kotori Ryou",
  "cover": "https://tritinia.com/wp-content/uploads/2021/02/24659-1-193x278.jpg",
  "chapters": {
    "38": {
      "title": "The Start of the Stampede",
      "volume": "7",
      "groups": {
        "Trtinia Scans": "/proxy/api/imgur/chapter/siVR85z/"
      },
      "last_updated": "1621761077"
    }
  }
}
